<?php
/**
 * @var \MODX\Revolution\modX $modx
 * @var array $namespace
 */

// Include autoloader generated by your composer
require_once $namespace['path'] . 'vendor/autoload.php';

if (!$modx->services->has('dashboards')) {
    // Register base class in the service container
    $modx->services->add('dashboards', function($c) use ($modx) {
        return new \MatDave\Dashboards\Service($modx);
    });

}

// More about this file: https://docs.modx.com/3.x/en/extending-modx/namespaces#bootstrapping-services
